### ISSUE TITLE
Option to switch project to JavaScript semicolon-less code style

### ISSUE THREAD

**Issue by steida** [este/este-cli#19]
I will add it since I am not using semicolons in my projects.

**Comment by grabbou** [comment]
Cool, can use `gulp.src` approach I am using in `lib/blueprint` and return a promise? :D That should work

**Comment by grabbou** [comment]
Made a simple boilerplate to get you started quicker.

https://github.com/grabbou/este-cli/blob/feature/colons/lib/tasks/toggle-semicolons.js
https://github.com/grabbou/este-cli/blob/feature/colons/lib/commands/semicolons.js

**Comment by grabbou** [comment]
This might be quite useful -> https://github.com/yyx990803/semi

**Comment by grabbou** [comment]
Wet dream is over :(

**Comment by steida** [comment]
It was more a loud protest then serious thing ;)
