### ISSUE TITLE
este-cli feature [name] creates wrong <Route/>?

### ISSUE THREAD

**Issue by rkoberg** [este/este-cli#29]
First, perhaps this should describe everything it does? It touches/creates a lot of stuff.
```shell
$ este-cli feature profile
[12:15:56] [conflict] Creating src/client/pages/profile.react.js
[12:15:56] [conflict] Creating src/client/profile/store.js
Task finished successfully
```
The route created in src/client/routes.js has different attributes than what comes in este:
```
    <Route name={Profile} path="profile" />
```
Where the other routes look like:
```
    <Route handler={Todos} name="todos"/>
```
Which results in an err (the link/menu item become visible when user is authenticated):
client/auth/login.react onFormSubmit response Error: Invariant Violation: Cannot find a route named "profile"

**Comment by grabbou** [comment]
Looks like to much prototyping by the evening ;) That's an easy one, will send over a fix by the morning. Thanks for reporting.
