### ISSUE TITLE
using the feature command appends 'Cursor' to cursor name. And should it revive?

### ISSUE THREAD

**Issue by rkoberg** [este/este-cli#30]
Perhaps naming it with 'Cursor' appended is a good practice, but that is not how the other cursors are named. Is it a bug?
```
export const todosCursor = state.cursor(['todos']);
export const usersCursor = state.cursor(['users']);
export const profileCursor = state.cursor(["profileCursor"]);
```
Also, should the feature command generate the revive file and add relevant info to client/state.js?

**Comment by grabbou** [comment]
Yeah, a bug! Seen it last week but forgot to create an issue. The second one should be w/o `cursor` and obviously ` ` ` instead of ` " `.
