### ISSUE TITLE
Error on new page

### ISSUE THREAD

**Issue by AugustinLF** [este/este-cli#46]
This shows in my console: `no value or default function given for field "id" of ImportDefaultSpecifier("local": Identifier)`.

The page is correctly created, I guess it cannot create the route. I'll try to have a look.

**Comment by AugustinLF** [comment]
So the problem seems to be in the creation of the import statement, more precisely in the creation of the `importDefaultSpecifier`:
```javascript
b.importDefaultSpecifier(
  b.identifier(pascalCase(options.blueprintName))
)
```
This starts to be a bit deep to me, considering the lack of nice API documentation for `ast-types` and `recast`. I'll see if I can make any progess on that, but since you're the one who coded that, perhaps you'll have a better idea.

**Comment by grabbou** [comment]
It's really hard to dive in, I know the pain ;)

**Comment by grabbou** [comment]
Fixed, but we need to rewrite the library with proper inheritance and method reusing
